# Generated by Django 5.1.5 on 2025-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
    ]
