# Generated by Django 5.1.5 on 2025-01-30 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="products",
        ),
    ]
