# Generated by Django 5.1.5 on 2025-01-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders_app", "0002_rename_product_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="cost",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
