# Generated by Django 5.1.5 on 2025-02-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("information_app", "0002_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="subscription",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Free"),
                    ("daily", "Daily"),
                    ("monthly", "Monthly"),
                    ("annual", "Annual"),
                ],
                default="free",
                max_length=64,
            ),
        ),
    ]
